### ISSUE TITLE
isn't there an arm64 version?

### ISSUE THREAD

**Issue by Nabhan87** [eko/pihole-exporter#130]

**Comment by Zozman** [comment]
Looking at [this comment in the buildx repo](https://github.com/docker/buildx/issues/166#issuecomment-544617936), [this line in the GitHub Actions workflow](https://github.com/eko/pihole-exporter/blob/master/.github/workflows/tag.yml#L51) that handles pushing the builds to the repository might need to be modified to `--output=type=registry,push=true \` in order to force buildx to push all the different builds as opposed to the default one.

**Comment by eko** [comment]
Hello,

The docker image is a multi-architecture docker image and yes, it also supports arm64, see here: https://hub.docker.com/layers/pihole-exporter/ekofr/pihole-exporter/latest/images/sha256-4be8d840f7b0823809fb1332fa8799621867dbed29232db168b9fd6e6f54baec?context=explore

Closing this issue but feel free to reopen if you still have an issue concerning arm64.

Thanks
