### ISSUE TITLE
Unable to login to PI-Hole, got a HTTP status code response '302' instead of '302'

### ISSUE THREAD

**Issue by apedance** [eko/pihole-exporter#15]
Ehm, what?

**Comment by RutgerKe** [comment]
I had the same, probably due to the latest commit: https://github.com/eko/pihole-exporter/commit/d72e73ce977242774acce569f8f893a97258581f, looking at the commit message it is due to an upgrade in pihole.

Downgrading to [ekofr/pihole-exporter:0.0.4](https://hub.docker.com/r/ekofr/pihole-exporter/tagsl) fixed it for my current setup, but it is probably also fixed by just upgrading pihole.

**Comment by eko** [comment]
Hi,

Thank you for reporting this issue. Maybe we should check for both 200 and 302 status codes to be « valid », this way it should work whatever depending the version
