### ISSUE TITLE
JSON Import in Grafana not Working

### ISSUE THREAD

**Issue by wuast94** [eko/pihole-exporter#28]
When i Import the raw json in Grafana and select the Prometheus datasource there is no data. i double checked all. 

![image](https://user-images.githubusercontent.com/16965460/75614473-5d039200-5b39-11ea-8a46-29c309a6568a.png)

and this is what i see when i edit a dashboard.. the datasource seems wrong there but why ? 

![image](https://user-images.githubusercontent.com/16965460/75614488-7e647e00-5b39-11ea-8762-06a3e2fe87a5.png)

**Comment by rth9** [comment]
Go to Configuration, Data Sources, switch Prometheus to your default and then go back to the dashboard. Once there, edit the query on each one to explicitly pick Prometheus as a data source rather than 'default'. Then you can go back and switch your data source to be Influx as your default (or any others).

**Comment by garymcleanuk** [comment]
Worked for me!!

**Comment by eko** [comment]
Thank you, closing this issue for now.
