### ISSUE TITLE
Pi-Hole Exporter Dashboard Doesn't Show Any Data By Default

### ISSUE THREAD

**Issue by GregHilston** [eko/pihole-exporter#3]
I am unable to get the [PI-Hole Exporter Dashboard](https://grafana.com/dashboards/10176) to display any data when using this project. I realize that the dashboard mentioned is not this project specifically, but perhaps you would know how to resolve this issue, as you also wrote the dashboard haha.

I've tried importing the dashboard by id (`10176`) and also by using its JSON and still have not been successful.

My setup _may_ differ from yours, as my Grafana and Prometheus installs are dockerized on some machine A and my pihole exporter is on some machine B. I've attempted to configure the JSON to point at the machine B, where the pihole exporter is running and have been successful at getting my own graphs to display, but not the ones in your dashboard.

Any thoughts or advice would be greatly appreciated, as your dashboard looks lovely.

**Comment by GregHilston** [comment]
@eko Any thoughts on this? If you have any idea, I'd be happy to go explore down that path

**Comment by eko** [comment]
Hi @GregHilston,

Sorry for the late answer.

Sorry but I've just tried to understand what's happening and I have no idea. Is your Prometheus server configured as a data source on your Grafana settings?

What you can also try is:

After importing the dashboard, go to dashboard settings and ensure you selected the right source here:

<img width="826" alt="Capture d’écran 2019-05-24 à 08 51 18" src="https://user-images.githubusercontent.com/103900/58308214-3e7da700-7e01-11e9-8869-debcbd6ffb7e.png">

**Comment by kendellmendoza** [comment]
Hi, same issue here. It seems that the problem  is due to the dashboard attempting to use the user's **Default** data source as opposed to using **Prometheus**. My Default was InfluxDB, but after changing it to Prometheus, all panels now display correctly.

![image](https://user-images.githubusercontent.com/32558172/58385304-446bb780-7fbc-11e9-95df-e0a73a13dd72.png)

**Comment by GregHilston** [comment]
@kendellmendoza @eko I'm going to try to provide as much information as possible, hopefully one of you will see the issue jump out at you. 

My UI looks strangely different from both of yours: 

![image](https://user-images.githubusercontent.com/4227776/58526149-49cb2c80-818b-11e9-8cfb-c3031552cefd.png)

Here is my data source, running on the same device but a different container
![image](https://user-images.githubusercontent.com/4227776/58526185-66676480-818b-11e9-9328-16a1262cb07b.png)

output of `$ docker ps`
![image](https://user-images.githubusercontent.com/4227776/58526237-8d259b00-818b-11e9-827a-e65426212105.png)

Proof I have data in prometheus: 

![image](https://user-images.githubusercontent.com/4227776/58526351-f1485f00-818b-11e9-9a80-754cb2e0b364.png)

I've attached my dashboard's config, as a `json` file (its labeled as a `txt` file, as github wouldn't let be attach a `json` file....

[pihole_dashboard_config.txt](https://github.com/eko/pihole-exporter/files/3230589/pihole_dashboard_config.txt)

**Comment by eko** [comment]
Hi @GregHilston,

It appears you are running Grafana v4.1.2 while we are running on v6.x versions. You could upgrade to this new version (only Grafana, which displays data) in order to have the same screens.

Moreover, Grafana has changed its Dashboard layout template since v5 (see: https://grafana.com/docs/guides/whats-new-in-v5/#new-dashboard-layout-engine) so I can’t ensure the dashboard will work on older versions.

Thank you

**Comment by eko** [comment]
Closing this issue as the dashboard is working on recent Grafana versions.

Thank you
